[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pystacker"
version = "1.8.2"
authors = [
    {name = "remokasu"}
]
description = "Stacker: RPN Calculator in Python"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["reverse-polish-calculator", "rpn", "terminal-app"]
dependencies = ["prompt-toolkit"]

[project.urls]
Homepage = "https://github.com/remokasu/stacker"

[project.scripts]
stacker = "stacker.__main__:main"

[tool.setuptools]
packages = ["stacker"]
package-data = {"stacker" = [
    "data/*",
    "plugins/*",
    "include/*",
    "exec_modes/*",
    "util/*",
    "syntax/*",
    "slib/*",
    "lib/*"
]}