#
# stacker src.sk
#

#######################
# example 1
#######################
"example 1" echo

1 3 +
ans echo

#######################
# example 2
#######################
"example 2" echo

[1 2 3] A set
[4 5 6] B set

{result: } A B .* string + echo

#######################
# example 3
#######################
"example 3" echo

[
 1 2 3;
 4 5 6;
10 11 2
] C set

C echo


#######################
# example 4
#######################
"example 4" echo

0 4 seq {0 4 seq {i j *} j for} i for D set
D echo


#######################
# example 5
#######################
"example 5" echo

0 4 seq {
    0 4 seq {
        i j ^ a set
    } j for
} i for

i echo
j echo
a echo
