#
# stacker src.sk
#

#######################
# example 1
#######################
"example 1" echo

1 3 +
ans echo

#######################
# example 2
#######################
"example 2" echo

[1 2 3] A set
[4 5 6] B set

{result: } A B .* str + echo

#######################
# example 3
#######################
"example 3" echo

[
 1 2 3;
 4 5 6;
10 11 2
] C set

C echo


#######################
# example 4
#######################
"example 4" echo

0 4 seq {0 4 seq {i j *} j for} i for D set
D echo


#######################
# example 5
#######################
"example 5" echo

0 4 seq {
    0 4 seq {
        0 5 seq {
            i j k + + a set
        } k for
    } j for
} i for


#######################
# example 6
#######################
"example 6" echo

0 s set
0 101 seq {
    s i 2 ^ + s set
    s echo
} i for
s echo